use mimic3_sepsis_cleaned;

#ALBUMIN
DROP TABLE IF EXISTS mimic3_sepsis_cleaned.ALBUMIN_CELE_CLEANED;
CREATE TABLE mimic3_sepsis_cleaned.ALBUMIN_CELE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'g/dL' ELSE VALUEUOM END AS VALUEUOM,
    'CE' AS SOURCE
FROM mimic3_sepsis_new.ALBUMIN_CE
WHERE VALUE REGEXP '^[0-9]*(\.[0-9]+)?$'AND (ERROR IS NULL OR ERROR = 0);
INSERT INTO mimic3_sepsis_cleaned.ALBUMIN_CELE_CLEANED (ICUSTAY_ID, ITEMID, CHARTTIME, VALUE, VALUEUOM, SOURCE)
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'g/dL' ELSE VALUEUOM END AS VALUEUOM,
    'LE' AS SOURCE
FROM mimic3_sepsis_new.ALBUMIN_LE
WHERE VALUE REGEXP '^[0-9]*(\.[0-9]+)?$';

#CALCIUM
CREATE TABLE CALCIUM_CELE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE
    WHEN ITEMID IN (816,3766,225667) THEN 'mmol/L'
    ELSE 'mg/dL'
END AS VALUEUOM,
    'CE' AS SOURCE
FROM mimic3_sepsis_new.CALCIUM_CE
WHERE VALUE REGEXP '^[0-9]*(\.[0-9]+)?$'AND (ERROR IS NULL OR ERROR = 0);
INSERT INTO CALCIUM_CELE_CLEANED (ICUSTAY_ID, ITEMID, CHARTTIME, VALUE, VALUEUOM, SOURCE)
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE
    WHEN VALUEUOM IS NULL AND ITEMID in (50808) THEN 'mmol/L'
    WHEN VALUEUOM IS NULL AND ITEMID in (50893)  THEN 'mg/dL'
    ELSE VALUEUOM
END AS VALUEUOM,
    'LE' AS SOURCE
FROM mimic3_sepsis_new.CALCIUM_LE
WHERE VALUE REGEXP '^[0-9]*(\.[0-9]+)?$';

#BASE_EXCESS
CREATE TABLE BASE_EXCESS_CELE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'mEq/L' ELSE VALUEUOM END AS VALUEUOM,
    'CE' AS SOURCE
FROM mimic3_sepsis_new.BASE_EXCESS_CE
WHERE VALUE REGEXP '^(-)?[0-9]+(\.[0-9]+)?$'AND (ERROR IS NULL OR ERROR = 0);
INSERT INTO BASE_EXCESS_CELE_CLEANED (ICUSTAY_ID, ITEMID, CHARTTIME, VALUE, VALUEUOM, SOURCE)
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'mEq/L' ELSE VALUEUOM END AS VALUEUOM,
    'LE' AS SOURCE
FROM mimic3_sepsis_new.BASE_EXCESS_LE
WHERE VALUE REGEXP '^(-)?[0-9]+(\.[0-9]+)?$';

#BILIRUBIN
CREATE TABLE BILIRUBIN_CELE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    'mg/dL ' AS VALUEUOM,
    'CE' AS SOURCE
FROM mimic3_sepsis_new.BILIRUBIN_CE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0) AND ITEMID in (225690);
INSERT INTO BILIRUBIN_CELE_CLEANED (ICUSTAY_ID, ITEMID, CHARTTIME, VALUE, VALUEUOM, SOURCE)
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'mg/dL' ELSE VALUEUOM END AS VALUEUOM,
    'LE' AS SOURCE
FROM mimic3_sepsis_new.BILIRUBIN_LE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$';

#CO2
CREATE TABLE CO2_CELE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'mEq/L' ELSE VALUEUOM END AS VALUEUOM,
    'CE' AS SOURCE
FROM mimic3_sepsis_new.CO2_CE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);
INSERT INTO CO2_CELE_CLEANED (ICUSTAY_ID, ITEMID, CHARTTIME, VALUE, VALUEUOM, SOURCE)
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'mEq/L' ELSE VALUEUOM END AS VALUEUOM,
    'LE' AS SOURCE
FROM mimic3_sepsis_new.CO2_LE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$';

#MAGNESIUM
CREATE TABLE MAGNESIUM_CELE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'mg/dL' ELSE VALUEUOM END AS VALUEUOM,
    'CE' AS SOURCE
FROM mimic3_sepsis_new.MAGNESIUM_CE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);
INSERT INTO MAGNESIUM_CELE_CLEANED (ICUSTAY_ID, ITEMID, CHARTTIME, VALUE, VALUEUOM, SOURCE)
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'mg/dL' ELSE VALUEUOM END AS VALUEUOM,
    'LE' AS SOURCE
FROM mimic3_sepsis_new.MAGNESIUM_LE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$';

CREATE TABLE PACO2_CELE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'mmHg' ELSE VALUEUOM END AS VALUEUOM,
    'CE' AS SOURCE
FROM mimic3_sepsis_new.PACO2_CE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);
INSERT INTO PACO2_CELE_CLEANED (ICUSTAY_ID, ITEMID, CHARTTIME, VALUE, VALUEUOM, SOURCE)
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    'mmHg' AS VALUEUOM,
    'LE' AS SOURCE
FROM mimic3_sepsis_new.PACO2_LE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$';

#PAO2
CREATE TABLE PAO2_CELE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'mmHg' ELSE VALUEUOM END AS VALUEUOM,
    'CE' AS SOURCE
FROM mimic3_sepsis_new.PAO2_CE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);
INSERT INTO PAO2_CELE_CLEANED (ICUSTAY_ID, ITEMID, CHARTTIME, VALUE, VALUEUOM, SOURCE)
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    'mmHg' AS VALUEUOM,
    'LE' AS SOURCE
FROM mimic3_sepsis_new.PAO2_LE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$';

#PT
CREATE TABLE PT_CELE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'sec' ELSE VALUEUOM END AS VALUEUOM,
    'CE' AS SOURCE
FROM mimic3_sepsis_new.PT_CE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);
INSERT INTO PT_CELE_CLEANED (ICUSTAY_ID, ITEMID, CHARTTIME, VALUE, VALUEUOM, SOURCE)
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    'sec' AS VALUEUOM,
    'LE' AS SOURCE
FROM mimic3_sepsis_new.PT_LE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$';

#PTT
CREATE TABLE PTT_CELE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'sec' ELSE VALUEUOM END AS VALUEUOM,
    'CE' AS SOURCE
FROM mimic3_sepsis_new.PTT_CE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);
INSERT INTO PTT_CELE_CLEANED (ICUSTAY_ID, ITEMID, CHARTTIME, VALUE, VALUEUOM, SOURCE)
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    'sec' AS VALUEUOM,
    'LE' AS SOURCE
FROM mimic3_sepsis_new.PTT_LE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$';

#INR
CREATE TABLE INR_CELE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    VALUEUOM,
    'CE' AS SOURCE
FROM mimic3_sepsis_new.INR_CE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);
INSERT INTO INR_CELE_CLEANED (ICUSTAY_ID, ITEMID, CHARTTIME, VALUE, VALUEUOM, SOURCE)
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    VALUEUOM,
    'LE' AS SOURCE
FROM mimic3_sepsis_new.INR_LE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$';

#LACTATE
CREATE TABLE LACTATE_CELE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'mmol/L' ELSE VALUEUOM END AS VALUEUOM,
    'LE' AS SOURCE
FROM mimic3_sepsis_new.INR_LE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$';

#PLATELET
CREATE TABLE PLATELET_CELE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'K/uL' ELSE VALUEUOM END AS VALUEUOM,
    'CE' AS SOURCE
FROM mimic3_sepsis_new.PLATELET_CE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);
INSERT INTO PLATELET_CELE_CLEANED (ICUSTAY_ID, ITEMID, CHARTTIME, VALUE, VALUEUOM, SOURCE)
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'K/uL' ELSE VALUEUOM END AS VALUEUOM,
    'LE' AS SOURCE
FROM mimic3_sepsis_new.PLATELET_LE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$';

#PH
CREATE TABLE PH_CELE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'units' ELSE VALUEUOM END AS VALUEUOM,
    'CE' AS SOURCE
FROM mimic3_sepsis_new.PH_CE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0) AND ITEMID in (780,1126,3839,4202,4753,220274);
INSERT INTO PH_CELE_CLEANED (ICUSTAY_ID, ITEMID, CHARTTIME, VALUE, VALUEUOM, SOURCE)
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'units' ELSE VALUEUOM END AS VALUEUOM,
    'LE' AS SOURCE
FROM mimic3_sepsis_new.PH_LE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$';

#BUN
CREATE TABLE BUN_CELE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'mg/dL' ELSE VALUEUOM END AS VALUEUOM,
    'CE' AS SOURCE
FROM mimic3_sepsis_new.BUN_CE
WHERE VALUE REGEXP '^[0-9]*(\.[0-9]+)?$'AND (ERROR IS NULL OR ERROR = 0);
INSERT INTO BUN_CELE_CLEANED (ICUSTAY_ID, ITEMID, CHARTTIME, VALUE, VALUEUOM, SOURCE)
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'mg/dL' ELSE VALUEUOM END AS VALUEUOM,
    'LE' AS SOURCE
FROM mimic3_sepsis_new.BUN_LE
WHERE VALUE REGEXP '^[0-9]*(\.[0-9]+)?$';

#Bicarbonate
CREATE TABLE BICARBONATE_CELE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'mEq/L' ELSE VALUEUOM END AS VALUEUOM,
    'LE' AS SOURCE
FROM mimic3_sepsis_new.BICARBONATE_LE
WHERE VALUE REGEXP '^[0-9]*(\.[0-9]+)?$';


#CHLORIDE
CREATE TABLE CHLORIDE_CELE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'mEq/L' ELSE VALUEUOM END AS VALUEUOM,
    'CE' AS SOURCE
FROM mimic3_sepsis_new.CHLORIDE_CE
WHERE VALUE REGEXP '^[0-9]*(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);
INSERT INTO CHLORIDE_CELE_CLEANED (ICUSTAY_ID, ITEMID, CHARTTIME, VALUE, VALUEUOM, SOURCE)
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'mEq/L' ELSE VALUEUOM END AS VALUEUOM,
    'LE' AS SOURCE
FROM mimic3_sepsis_new.CHLORIDE_LE
WHERE VALUE REGEXP '^[0-9]*(\.[0-9]+)?$';

#CREATININE
CREATE TABLE CREATININE_CELE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'mg/dL' ELSE VALUEUOM END AS VALUEUOM,
    'CE' AS SOURCE
FROM mimic3_sepsis_new.CREATININE_CE
WHERE VALUE REGEXP '^[0-9]*(\.[0-9]+)?$'AND (ERROR IS NULL OR ERROR = 0);
INSERT INTO CREATININE_CELE_CLEANED (ICUSTAY_ID, ITEMID, CHARTTIME, VALUE, VALUEUOM, SOURCE)
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'mg/dL' ELSE VALUEUOM END AS VALUEUOM,
    'LE' AS SOURCE
FROM mimic3_sepsis_new.CREATININE_LE
WHERE VALUE REGEXP '^[0-9]*(\.[0-9]+)?$';

#GLUCOSE
CREATE TABLE GLUCOSE_CELE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'mg/dL' ELSE VALUEUOM END AS VALUEUOM,
    'CE' AS SOURCE
FROM mimic3_sepsis_new.GLUCOSE_CE
WHERE VALUE REGEXP '^[0-9]*(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);
INSERT INTO GLUCOSE_CELE_CLEANED (ICUSTAY_ID, ITEMID, CHARTTIME, VALUE, VALUEUOM, SOURCE)
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'mg/dL' ELSE VALUEUOM END AS VALUEUOM,
    'LE' AS SOURCE
FROM mimic3_sepsis_new.GLUCOSE_LE
WHERE VALUE REGEXP '^[0-9]*(\.[0-9]+)?$';

#POTASSIUM
CREATE TABLE POTASSIUM_CELE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'mEq/L' ELSE VALUEUOM END AS VALUEUOM,
    'CE' AS SOURCE
FROM mimic3_sepsis_new.POTASSIUM_CE
WHERE VALUE REGEXP '^[0-9]*(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);
INSERT INTO POTASSIUM_CELE_CLEANED (ICUSTAY_ID, ITEMID, CHARTTIME, VALUE, VALUEUOM, SOURCE)
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'mEq/L' ELSE VALUEUOM END AS VALUEUOM,
    'LE' AS SOURCE
FROM mimic3_sepsis_new.POTASSIUM_LE
WHERE VALUE REGEXP '^[0-9]*(\.[0-9]+)?$';

#SODIUM
CREATE TABLE SODIUM_CELE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'mEq/L' ELSE VALUEUOM END AS VALUEUOM,
    'CE' AS SOURCE
FROM mimic3_sepsis_new.SODIUM_CE
WHERE VALUE REGEXP '^[0-9]*(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);
INSERT INTO SODIUM_CELE_CLEANED (ICUSTAY_ID, ITEMID, CHARTTIME, VALUE, VALUEUOM, SOURCE)
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'mEq/L' ELSE VALUEUOM END AS VALUEUOM,
    'LE' AS SOURCE
FROM mimic3_sepsis_new.SODIUM_LE
WHERE VALUE REGEXP '^[0-9]*(\.[0-9]+)?$';

#WBC
CREATE TABLE WBC_CELE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'K/uL' ELSE VALUEUOM END AS VALUEUOM,
    'CE' AS SOURCE
FROM mimic3_sepsis_new.WBC_CE
WHERE VALUE REGEXP '^[0-9]*(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);
INSERT INTO WBC_CELE_CLEANED (ICUSTAY_ID, ITEMID, CHARTTIME, VALUE, VALUEUOM, SOURCE)
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'K/uL' ELSE VALUEUOM END AS VALUEUOM,
    'LE' AS SOURCE
FROM mimic3_sepsis_new.WBC_LE
WHERE VALUE REGEXP '^[0-9]*(\.[0-9]+)?$';

#HEMOGLOBIN
CREATE TABLE HEMOGLOBIN_CELE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    'g/dl' AS VALUEUOM,
    'CE' AS SOURCE
FROM mimic3_sepsis_new.HEMOGLOBIN_CE
WHERE VALUE REGEXP '^[0-9]*(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0) AND ITEMID in (814,220228);
INSERT INTO HEMOGLOBIN_CELE_CLEANED (ICUSTAY_ID, ITEMID, CHARTTIME, VALUE, VALUEUOM, SOURCE)
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE
    WHEN VALUEUOM IS NULL AND ITEMID in (50811) THEN 'g/dL'
    WHEN VALUEUOM IS NULL AND ITEMID in (51222)  THEN 'g/dL'
    ELSE VALUEUOM
END AS VALUEUOM,
    'LE' AS SOURCE
FROM mimic3_sepsis_new.HEMOGLOBIN_LE
WHERE ITEMID in (50811,51222) AND VALUE REGEXP '^[0-9]*(\.[0-9]+)?$';

#Bicarbonate
DROP TABLE IF EXISTS BICARBONATE_CELE_CLEANED;
CREATE TABLE BICARBONATE_CELE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'mEq/L' ELSE VALUEUOM END AS VALUEUOM,
    'CE' AS SOURCE
FROM mimic3_sepsis_new.BICARBONATE_CE
WHERE VALUE REGEXP '^[0-9]*(\.[0-9]+)?$'AND (ERROR IS NULL OR ERROR = 0);
INSERT INTO BICARBONATE_CELE_CLEANED (ICUSTAY_ID, ITEMID, CHARTTIME, VALUE, VALUEUOM, SOURCE)
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'mEq/L' ELSE VALUEUOM END AS VALUEUOM,
    'LE' AS SOURCE
FROM mimic3_sepsis_new.BICARBONATE_LE
WHERE VALUE REGEXP '^[0-9]*(\.[0-9]+)?$';

#CRP
CREATE TABLE mimic3_sepsis_cleaned.CRP_CELE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'mg/L' ELSE VALUEUOM END AS VALUEUOM,
    'CE' AS SOURCE
FROM mimic3_sepsis_new.CRP_CE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);
INSERT INTO mimic3_sepsis_cleaned.CRP_CELE_CLEANED (ICUSTAY_ID, ITEMID, CHARTTIME, VALUE, VALUEUOM, SOURCE)
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'mg/L' ELSE VALUEUOM END AS VALUEUOM,
    'LE' AS SOURCE
FROM mimic3_sepsis_new.CRP_LE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$';

#ACT
CREATE TABLE mimic3_sepsis_cleaned.ACT_CELE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 's' ELSE VALUEUOM END AS VALUEUOM,
    'CE' AS SOURCE
FROM mimic3_sepsis_new.ACT_CE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);

#CARDIAC_INDEX
DROP TABLE IF EXISTS mimic3_sepsis_cleaned.CARDIAC_INDEX_CLEANED;
CREATE TABLE mimic3_sepsis_cleaned.CARDIAC_INDEX_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL or VALUEUOM = '...' THEN 'L/min/m2' ELSE VALUEUOM END AS VALUEUOM
FROM mimic3_sepsis_new.CARDIAC_INDEX
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);

#CVP
DROP TABLE IF EXISTS mimic3_sepsis_cleaned.CVP_CLEANED;
CREATE TABLE mimic3_sepsis_cleaned.CVP_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL or VALUEUOM = '%' THEN 'mmHg' ELSE VALUEUOM END AS VALUEUOM
FROM mimic3_sepsis_new.CVP
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);

#ETCO2
CREATE TABLE mimic3_sepsis_cleaned.ETCO2_CELE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'mmHg' ELSE VALUEUOM END AS VALUEUOM,
    'CE' AS SOURCE
FROM mimic3_sepsis_new.ETCO2_CE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);

#HEART_RATE
DROP TABLE IF EXISTS mimic3_sepsis_cleaned.HEART_RATE_CLEANED;
CREATE TABLE mimic3_sepsis_cleaned.HEART_RATE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL or VALUEUOM = '%' THEN 'mmHg' ELSE VALUEUOM END AS VALUEUOM
FROM mimic3_sepsis_new.HEART_RATE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);

#HEMATOCRIT
CREATE TABLE mimic3_sepsis_cleaned.HEMATOCRIT_CELE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN '%' ELSE VALUEUOM END AS VALUEUOM,
    'CE' AS SOURCE
FROM mimic3_sepsis_new.HEMATOCRIT_CE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);
INSERT INTO mimic3_sepsis_cleaned.HEMATOCRIT_CELE_CLEANED (ICUSTAY_ID, ITEMID, CHARTTIME, VALUE, VALUEUOM, SOURCE)
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN '%' ELSE VALUEUOM END AS VALUEUOM,
    'LE' AS SOURCE
FROM mimic3_sepsis_new.HEMATOCRIT_LE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$';

#MINUTE_VOLUME
DROP TABLE IF EXISTS mimic3_sepsis_cleaned.MINUTE_VOLUME_CLEANED;
CREATE TABLE mimic3_sepsis_cleaned.MINUTE_VOLUME_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'L/min' ELSE VALUEUOM END AS VALUEUOM
FROM mimic3_sepsis_new.MINUTE_VOLUME
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);

#O2_DELI_DEV
DROP TABLE IF EXISTS mimic3_sepsis_cleaned.O2_DELI_DEV_CLEANED;
CREATE TABLE mimic3_sepsis_cleaned.O2_DELI_DEV_CLEANED
SELECT ICUSTAY_ID, ITEMID, CHARTTIME,
       case
           when value = 'None' then '0'
           when value = 'Ventilator' then '1'
           when value='Cannula' then '2'
           when value = 'Nasal Cannula' then '2'
           when value = 'Face Tent' then '3'
           when value = 'Aerosol-Cool' then '4'
           when value = 'Trach Mask' then '5'
           when value = 'Hi Flow Neb' then '6'
           when value = 'Non-Rebreather' then '7'
           when value = '' then '8'
           when value = 'Venti Mask' then '9'
           when value = 'Medium Conc Mask' then '10' else VALUENUM END AS VALUE
FROM mimic3_sepsis_new.O2_DELI_DEV;



#O2_FLOW
DROP TABLE IF EXISTS mimic3_sepsis_cleaned.O2_FLOW_CLEANED;
CREATE TABLE mimic3_sepsis_cleaned.O2_FLOW_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'lpm' ELSE VALUEUOM END AS VALUEUOM
FROM mimic3_sepsis_new.O2_FLOW
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);

#RASS
DROP TABLE IF EXISTS mimic3_sepsis_cleaned.RASS_CLEANED;
CREATE TABLE mimic3_sepsis_cleaned.RASS_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    VALUEUOM
FROM mimic3_sepsis_new.RASS
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);

#RBC
CREATE TABLE mimic3_sepsis_cleaned.RBC_CELE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN '/mic l' ELSE VALUEUOM END AS VALUEUOM,
    'CE' AS SOURCE
FROM mimic3_sepsis_new.RBC_CE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);
INSERT INTO mimic3_sepsis_cleaned.RBC_CELE_CLEANED (ICUSTAY_ID, ITEMID, CHARTTIME, VALUE, VALUEUOM, SOURCE)
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'm/uL' ELSE VALUEUOM END AS VALUEUOM,
    'LE' AS SOURCE
FROM mimic3_sepsis_new.RBC_LE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$';

#RESP_RATE
DROP TABLE IF EXISTS mimic3_sepsis_cleaned.RESP_RATE_CLEANED;
CREATE TABLE mimic3_sepsis_cleaned.RESP_RATE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'BPM' ELSE VALUEUOM END AS VALUEUOM
FROM mimic3_sepsis_new.RESP_RATE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);

#SGOT
CREATE TABLE mimic3_sepsis_cleaned.SGOT_CELE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'IU/L' ELSE VALUEUOM END AS VALUEUOM,
    'CE' AS SOURCE
FROM mimic3_sepsis_new.SGOT_CE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);
INSERT INTO mimic3_sepsis_cleaned.SGOT_CELE_CLEANED (ICUSTAY_ID, ITEMID, CHARTTIME, VALUE, VALUEUOM, SOURCE)
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'IU/L' ELSE VALUEUOM END AS VALUEUOM,
    'LE' AS SOURCE
FROM mimic3_sepsis_new.SGOT_LE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$';

#SGPT
CREATE TABLE mimic3_sepsis_cleaned.SGPT_CELE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'IU/L' ELSE VALUEUOM END AS VALUEUOM,
    'CE' AS SOURCE
FROM mimic3_sepsis_new.SGPT_CE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);
INSERT INTO mimic3_sepsis_cleaned.SGPT_CELE_CLEANED (ICUSTAY_ID, ITEMID, CHARTTIME, VALUE, VALUEUOM, SOURCE)
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'IU/L' ELSE VALUEUOM END AS VALUEUOM,
    'LE' AS SOURCE
FROM mimic3_sepsis_new.SGPT_LE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$';

#SPO2
DROP TABLE IF EXISTS mimic3_sepsis_cleaned.SPO2_CLEANED;
CREATE TABLE mimic3_sepsis_cleaned.SPO2_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN '%' ELSE VALUEUOM END AS VALUEUOM
FROM mimic3_sepsis_new.SPO2
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);

#SPO2
DROP TABLE IF EXISTS mimic3_sepsis_cleaned.SPO2_CLEANED;
CREATE TABLE mimic3_sepsis_cleaned.SPO2_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN '%' ELSE VALUEUOM END AS VALUEUOM
FROM mimic3_sepsis_new.SPO2
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);

#SVO2
CREATE TABLE mimic3_sepsis_cleaned.SVO2_CELE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN '%' ELSE VALUEUOM END AS VALUEUOM,
    'CE' AS SOURCE
FROM mimic3_sepsis_new.SVO2_CE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);

#SVRI
DROP TABLE IF EXISTS mimic3_sepsis_cleaned.SVRI_CLEANED;
CREATE TABLE mimic3_sepsis_cleaned.SVRI_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'dynes.sec.cm-5/m2' ELSE VALUEUOM END AS VALUEUOM
FROM mimic3_sepsis_new.SVRI
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);

#TEMPERATURE
DROP TABLE IF EXISTS mimic3_sepsis_cleaned.TEMPERATURE_CLEANED;
CREATE TABLE mimic3_sepsis_cleaned.TEMPERATURE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL AND ITEMID in (676,677)THEN 'Deg. C'
    WHEN VALUEUOM IS NULL AND ITEMID in (678,679)THEN 'Deg. F'
    ELSE VALUEUOM END AS VALUEUOM
FROM mimic3_sepsis_new.TEMPERATURE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);

#TEMPERATURE
DROP TABLE IF EXISTS mimic3_sepsis_cleaned.TEMPERATURE_CLEANED;
CREATE TABLE mimic3_sepsis_cleaned.TEMPERATURE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL AND ITEMID in (676,677)THEN 'Deg. C'
    WHEN VALUEUOM IS NULL AND ITEMID in (678,679)THEN 'Deg. F'
    ELSE VALUEUOM END AS VALUEUOM
FROM mimic3_sepsis_new.TEMPERATURE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);

#TOTAL_PROTEIN
CREATE TABLE mimic3_sepsis_cleaned.TOTAL_PROTEIN_CELE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'g/dL' ELSE VALUEUOM END AS VALUEUOM,
    'CE' AS SOURCE
FROM mimic3_sepsis_new.TOTAL_PROTEIN_CE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);
INSERT INTO mimic3_sepsis_cleaned.TOTAL_PROTEIN_CELE_CLEANED (ICUSTAY_ID, ITEMID, CHARTTIME, VALUE, VALUEUOM, SOURCE)
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'g/dL' ELSE VALUEUOM END AS VALUEUOM,
    'LE' AS SOURCE
FROM mimic3_sepsis_new.TOTAL_PROTEIN_LE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$';

#TROPONIN
CREATE TABLE mimic3_sepsis_cleaned.TROPONIN_CELE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'ng/mL' ELSE VALUEUOM END AS VALUEUOM,
    'CE' AS SOURCE
FROM mimic3_sepsis_new.TROPONIN_CE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);
INSERT INTO mimic3_sepsis_cleaned.TROPONIN_CELE_CLEANED (ICUSTAY_ID, ITEMID, CHARTTIME, VALUE, VALUEUOM, SOURCE)
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'ng/mL' ELSE VALUEUOM END AS VALUEUOM,
    'LE' AS SOURCE
FROM mimic3_sepsis_new.TROPONIN_LE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$';

#TEMPERATURE
DROP TABLE IF EXISTS mimic3_sepsis_cleaned.TEMPERATURE_CLEANED;
CREATE TABLE mimic3_sepsis_cleaned.TEMPERATURE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL AND ITEMID in (676,677)THEN 'Deg. C'
    WHEN VALUEUOM IS NULL AND ITEMID in (678,679)THEN 'Deg. F'
    ELSE VALUEUOM END AS VALUEUOM
FROM mimic3_sepsis_new.TEMPERATURE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);

#HEIGHT
DROP TABLE IF EXISTS mimic3_sepsis_cleaned.HEIGHT_CLEANED;
CREATE TABLE mimic3_sepsis_cleaned.HEIGHT_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    VALUEUOM
FROM mimic3_sepsis_new.HEIGHT
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);

#PAP_DIA
DROP TABLE IF EXISTS mimic3_sepsis_cleaned.PAP_DIA_CLEANED;
CREATE TABLE mimic3_sepsis_cleaned.PAP_DIA_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    VALUEUOM
FROM mimic3_sepsis_new.PAP_DIA
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);

#PAP_MEAN
DROP TABLE IF EXISTS mimic3_sepsis_cleaned.PAP_MEAN_CLEANED;
CREATE TABLE mimic3_sepsis_cleaned.PAP_MEAN_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'mmHg' ELSE VALUEUOM END AS VALUEUOM
FROM mimic3_sepsis_new.PAP_MEAN
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);

#PAP_SYS
DROP TABLE IF EXISTS mimic3_sepsis_cleaned.PAP_SYS_CLEANED;
CREATE TABLE mimic3_sepsis_cleaned.PAP_SYS_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'mmHg' ELSE VALUEUOM END AS VALUEUOM
FROM mimic3_sepsis_new.PAP_SYS
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);

#PAW_PEAK
DROP TABLE IF EXISTS mimic3_sepsis_cleaned.PAW_PEAK_CLEANED;
CREATE TABLE mimic3_sepsis_cleaned.PAW_PEAK_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'cmH2O' ELSE VALUEUOM END AS VALUEUOM
FROM mimic3_sepsis_new.PAW_PEAK
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);

#PAW_MEAN
DROP TABLE IF EXISTS mimic3_sepsis_cleaned.PAW_MEAN_CLEANED;
CREATE TABLE mimic3_sepsis_cleaned.PAW_MEAN_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'cmH2O' ELSE VALUEUOM END AS VALUEUOM
FROM mimic3_sepsis_new.PAW_MEAN
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);

#PAW_PLATEAU
DROP TABLE IF EXISTS mimic3_sepsis_cleaned.PAW_PLATEAU_CLEANED;
CREATE TABLE mimic3_sepsis_cleaned.PAW_PLATEAU_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'cmH2O' ELSE VALUEUOM END AS VALUEUOM
FROM mimic3_sepsis_new.PAW_PLATEAU
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);

DROP TABLE IF EXISTS mimic3_sepsis_cleaned.WEIGHT_CLEANED;
CREATE TABLE mimic3_sepsis_cleaned.WEIGHT_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'kg' ELSE VALUEUOM END AS VALUEUOM
FROM mimic3_sepsis_new.WEIGHT
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);

DROP TABLE IF EXISTS mimic3_sepsis_cleaned.GCS_CLEANED;
CREATE TABLE mimic3_sepsis_cleaned.GCS_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'points' ELSE VALUEUOM END AS VALUEUOM
FROM mimic3_sepsis_new.GCS
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);


DROP TABLE IF EXISTS mimic3_sepsis_cleaned.FIO2_CLEANED;
CREATE TABLE mimic3_sepsis_cleaned.FIO2_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN (VALUEUOM IS NULL AND ITEMID = 190 )THEN 'torr'
        WHEN (VALUEUOM IS NULL AND VALUE != 190 )THEN '%'
        ELSE VALUEUOM END AS VALUEUOM
FROM mimic3_sepsis_new.FIO2
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);

DROP TABLE IF EXISTS mimic3_sepsis_cleaned.PEEP_CLEANED;
CREATE TABLE mimic3_sepsis_cleaned.PEEP_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'cmH2O' ELSE VALUEUOM END AS VALUEUOM
FROM mimic3_sepsis_new.PEEP
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);

DROP TABLE IF EXISTS mimic3_sepsis_cleaned.PLATEAU_PRESSURE_CLEANED;
CREATE TABLE mimic3_sepsis_cleaned.PLATEAU_PRESSURE_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'cmH2O' ELSE VALUEUOM END AS VALUEUOM
FROM mimic3_sepsis_new.PLATEAU_PRESSURE
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);

DROP TABLE IF EXISTS mimic3_sepsis_cleaned.BP_MEAN_CLEANED;
CREATE TABLE mimic3_sepsis_cleaned.BP_MEAN_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'mmHg' ELSE VALUEUOM END AS VALUEUOM
FROM mimic3_sepsis_new.BP_MEAN
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0)
AND ITEMID in (52,443,456,6702,220052,220181,225312);


DROP TABLE IF EXISTS mimic3_sepsis_cleaned.BP_SYS_CLEANED;
CREATE TABLE mimic3_sepsis_cleaned.BP_SYS_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'mmHg' ELSE VALUEUOM END AS VALUEUOM
FROM mimic3_sepsis_new.BP_SYS
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0)
AND ITEMID in (6,51,442,455,480,482,484,6701,220050,220179,224167,225309,227243);

DROP TABLE IF EXISTS mimic3_sepsis_cleaned.BP_DIA_CLEANED;
CREATE TABLE mimic3_sepsis_cleaned.BP_DIA_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN 'mmHg' ELSE VALUEUOM END AS VALUEUOM
FROM mimic3_sepsis_new.BP_DIA
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0)
AND ITEMID in (8364,8368,8440,8444,8445,8446,8555,220051,220180,224643,225310,227242);

DROP TABLE IF EXISTS mimic3_sepsis_cleaned.SVR_CLEANED;
CREATE TABLE mimic3_sepsis_cleaned.SVR_CLEANED AS
SELECT
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    VALUE,
    CASE WHEN VALUEUOM IS NULL THEN '...' ELSE VALUEUOM END AS VALUEUOM
FROM mimic3_sepsis_new.SVR
WHERE VALUE REGEXP '^(?:[0-9]+)?(\.[0-9]+)?$' AND (ERROR IS NULL OR ERROR = 0);

CREATE TABLE mimic3_sepsis_cleaned.ALL_VASO_MV AS
    SELECT * FROM mimic3_sepsis_new.DOPAMINE_MV
    WHERE 1=0;
INSERT INTO mimic3_sepsis_cleaned.ALL_VASO_MV SELECT * FROM mimic3_sepsis_new.VASOPRESSIN_MV;
INSERT INTO mimic3_sepsis_cleaned.ALL_VASO_MV SELECT * FROM mimic3_sepsis_new.DOPAMINE_MV;
INSERT INTO mimic3_sepsis_cleaned.ALL_VASO_MV SELECT * FROM mimic3_sepsis_new.EPINEPHRINE_MV;
INSERT INTO mimic3_sepsis_cleaned.ALL_VASO_MV SELECT * FROM mimic3_sepsis_new.NOREPINEPHRINE_MV;
INSERT INTO mimic3_sepsis_cleaned.ALL_VASO_MV SELECT * FROM mimic3_sepsis_new.PHENYLEPHRINE_MV;

CREATE TABLE mimic3_sepsis_cleaned.ALL_VASO_CV AS
    SELECT * FROM mimic3_sepsis_new.DOPAMINE_CV
    WHERE 1=0;
INSERT INTO mimic3_sepsis_cleaned.ALL_VASO_CV SELECT * FROM mimic3_sepsis_new.VASOPRESSIN_CV;
INSERT INTO mimic3_sepsis_cleaned.ALL_VASO_CV SELECT * FROM mimic3_sepsis_new.DOPAMINE_CV;
INSERT INTO mimic3_sepsis_cleaned.ALL_VASO_CV SELECT * FROM mimic3_sepsis_new.EPINEPHRINE_CV;
INSERT INTO mimic3_sepsis_cleaned.ALL_VASO_CV SELECT * FROM mimic3_sepsis_new.NOREPINEPHRINE_CV;
INSERT INTO mimic3_sepsis_cleaned.ALL_VASO_CV SELECT * FROM mimic3_sepsis_new.PHENYLEPHRINE_CV;

#Culture
USE mimic3_sepsis_cleaned;
CREATE TABLE CULTURE_CE AS
select subject_id, hadm_id, icustay_id, charttime, itemid, error
FROM mimic3.CHARTEVENTS
WHERE (ERROR IS NULL OR ERROR = 0)
and itemid in
(938,941,942,2929,3333,4855,6035,6043,225722,225723,225724,
225725,225726,225727,225728,225729,225730,225731,225732,
225733,225734,225735,225736,225768,226131,227726)
order by subject_id, hadm_id, charttime;

CREATE TABLE CULTURE_ME AS
-- Culture, in MICROBIOLOGYEVENTS
select subject_id, hadm_id,
(case when CHARTTIME IS NULL then CHARTDATE ELSE CHARTTIME end) AS charttime,
spec_itemid as itemid
FROM mimic3.MICROBIOLOGYEVENTS
where spec_itemid in
(70006,70011,70012,70013,70014,70016,70024,70037,70041,70055,
70057,70060,70063,70075,70083,80220)
order by subject_id, hadm_id, charttime;

CREATE TABLE CULTURE_PE AS
-- Culture, in PROCEDUREEVENTS_MV
select subject_id, hadm_id, icustay_id, endtime as charttime, itemid
FROM mimic3.PROCEDUREEVENTS_MV
WHERE STATUSDESCRIPTION != 'Rewritten'
and itemid in
(225401,225437,225444,225451,225454,225814,225816,225817,225818)
order by subject_id, hadm_id, charttime;

-- ALL MICROBIOLOGYEVENTS
CREATE TABLE mimic3_sepsis_new.ME AS
select subject_id, hadm_id,
(case when CHARTTIME IS NULL then CHARTDATE ELSE CHARTTIME end) AS charttime
FROM mimic3.MICROBIOLOGYEVENTS;

#Antibiotics administration:
CREATE TABLE mimic3_sepsis_cleaned.ANTIBIOTICS AS
select subject_id, hadm_id, icustay_id, startdate, enddate
from mimic3.PRESCRIPTIONS
where gsn in ('002542','002543','007371','008873','008877',
'008879','008880','008935','008941','008942','008943','008944',
'008983','008984','008990','008991','008992','008995','008996',
'008998','009043','009046','009065','009066','009136','009137',
'009162','009164','009165','009171','009182','009189','009213',
'009214','009218','009219','009221','009226','009227','009235',
'009242','009263','009273','009284','009298','009299','009310',
'009322','009323','009326','009327','009339','009346','009351',
'009354','009362','009394','009395','009396','009509','009510',
'009511','009544','009585','009591','009592','009630','013023',
'013645','013723','013724','013725','014182','014500','015979',
'016368','016373','016408','016931','016932','016949','018636',
'018637','018766','019283','021187','021205','021735','021871',
'023372','023989','024095','024194','024668','025080','026721',
'027252','027465','027470','029325','029927','029928','037042',
'039551','039806','040819','041798','043350','043879','044143',
'045131','045132','046771','047797','048077','048262','048266',
'048292','049835','050442','050443','051932','052050','060365',
'066295','067471')
order by subject_id, hadm_id, icustay_id;

#DEMOGRAPHICS
CREATE TABLE mimic3_sepsis_cleaned.DEMOGRAPHICS AS
SELECT
	ad.subject_id, ad.hadm_id, i.icustay_id, ad.admittime, ad.dischtime,
	ROW_NUMBER() OVER (PARTITION BY ad.subject_id ORDER BY i.intime ASC) AS adm_order,
	CASE
		WHEN i.first_careunit='NICU' THEN 5
		WHEN i.first_careunit='SICU' THEN 2
		WHEN i.first_careunit='CSRU' THEN 4
		WHEN i.first_careunit='CCU' THEN 6
		WHEN i.first_careunit='MICU' THEN 1
		WHEN i.first_careunit='TSICU' THEN 3
	END AS unit,
	i.intime, i.outtime, i.los,
	TIMESTAMPDIFF(YEAR, p.dob, i.intime) AS age,
	p.dob, p.dod,
	p.expire_flag,
	CASE
		WHEN p.gender='M' THEN 1
		WHEN p.gender='F' THEN 2
	END AS gender,
	CASE
		WHEN TIMESTAMPDIFF(SECOND, p.dod, ad.dischtime) <= 24*3600 THEN 1
		ELSE 0
	END AS morta_hosp,
	CASE
		WHEN TIMESTAMPDIFF(SECOND, p.dod, i.intime) <= 90*24*3600 THEN 1
		ELSE 0
	END AS morta_90,
	congestive_heart_failure + cardiac_arrhythmias +
	valvular_disease + pulmonary_circulation + peripheral_vascular +
	hypertension + paralysis + other_neurological + chronic_pulmonary +
	diabetes_uncomplicated + diabetes_complicated + hypothyroidism +
	renal_failure + liver_disease + peptic_ulcer + aids + lymphoma +
	metastatic_cancer + solid_tumor + rheumatoid_arthritis + coagulopathy +
	obesity + weight_loss + fluid_electrolyte + blood_loss_anemia +
	deficiency_anemias + alcohol_abuse + drug_abuse + psychoses +
	depression AS elixhauser
FROM
	mimic3.ADMISSIONS ad,
	mimic3.ICUSTAYS i,
	mimic3.PATIENTS p,
	mimic3.elixhauser_quan elix
where
	ad.hadm_id=i.hadm_id and
	p.subject_id=i.subject_id and
	elix.hadm_id=ad.hadm_id
order by
	subject_id asc, intime asc

#Real-time UO
CREATE TABLE mimic3_sepsis_cleaned.UO AS
select icustay_id, charttime, itemid, value, valueuom
from mimic3.OUTPUTEVENTS
where icustay_id is not null and value is not null
and itemid in
(40055 ,43175 ,40069, 40094 ,40715 ,40473 ,40085,
40057, 40056 ,40405 ,40428, 40096, 40651,226559,
226560 ,227510 ,226561 ,227489 ,226584, 226563,
226564 ,226565 ,226557 ,226558)
order by icustay_id, charttime, itemid;

#preadmission-uo
CREATE TABLE mimic3_sepsis_cleaned.PREADM_UO AS
select distinct oe.icustay_id, oe.charttime, oe.itemid, oe.value, oe.valueuom,
TIMESTAMPDIFF(MINUTE , oe.charttime, ic.intime) as datediff_minutes
from mimic3.OUTPUTEVENTS oe, mimic3.ICUSTAYS ic
where oe.icustay_id=ic.icustay_id
and itemid in (40060,226633)
order by icustay_id, charttime, itemid

#preadm_fluid
CREATE TABLE mimic3_sepsis_cleaned.PREADM_FLUID AS
with mv as
(
select ie.icustay_id, sum(ie.amount) as sum
from mimic3.INPUTEVENTS_MV ie, mimic3.D_ITEMS ci
where ie.itemid=ci.itemid and ie.itemid in
(30054,30055,30101,30102,30103,30104,30105,30108,226361,226363,226364,
226365,226367,226368,226369,226370,226371,226372,226375,226376,227070,
227071,227072)
group by icustay_id
),

cv as
(
select ie.icustay_id, sum(ie.amount) as sum
from mimic3.INPUTEVENTS_CV ie, mimic3.D_ITEMS ci
where ie.itemid=ci.itemid and ie.itemid in
(30054,30055,30101,30102,30103,30104,30105,30108,226361,226363,226364,
226365,226367,226368,226369,226370,226371,226372,226375,226376,227070,
227071,227072)
group by icustay_id
)

select pt.icustay_id,
case when mv.sum is not null then mv.sum
when cv.sum is not null then cv.sum
else null end as inputpreadm
from mimic3.ICUSTAYS pt
left outer join mv
on mv.icustay_id=pt.icustay_id
left outer join cv
on cv.icustay_id=pt.icustay_id
order by icustay_id

#mech_vent
CREATE TABLE mimic3_sepsis_cleaned.MECHVENT AS

select ce.ICUSTAY_ID, ce.CHARTTIME,
    max(
    case
      when itemid is null or value is null then 0 -- can't have null values
      when itemid = 720 and value != 'Other/Remarks' THEN 1  -- VentTypeRecorded
      when itemid = 223848 and value != 'Other' THEN 1
      when itemid = 223849 then 1 -- ventilator mode
      when itemid = 467 and value = 'Ventilator' THEN 1 -- O2 delivery device == ventilator
      when itemid in
        (
        445, 448, 449, 450, 1340, 1486, 1600, 224687 -- minute volume
        , 639,654,681,682,683,684,2400,2408,2420,2534,3050,3083,224685,224684,224686 -- tidal volume
        , 218,436,535,444,459,224697,224695,224696,224746,224747 -- High/Low/Peak/Mean/Neg insp force ("RespPressure")
        , 221,1,1211,1655,2000,226873,224738,224419,224750,227187 -- Insp pressure
        , 543,224696 -- Plateau Pressure
        , 5865,5866,224707,224709,224705,224706 -- APRV pressure
        , 60,437,505,506,686,1096,1227,5964,6349,6350,6489,6601,6924,6943,7802,7803,220339,224699,224700 -- PEEP
        , 3459 -- high pressure relief
        , 501,502,503,224702 -- PCV
        , 223,667,668,669,670,671,672 -- TCPCV
        , 224701 -- PSVlevel
        )
        THEN 1
      else 0
    end
    ) as MechVent,
    max(
	case when itemid is null or value is null then 0
	 when itemid = 640 and value = 'Extubated' then 1
	 when itemid = 640 and value = 'Self Extubation' then 1
	 else 0
	 end
	) as Extubated,
	max(
	 case when itemid is null or value is null then 0
	 when itemid = 640 and value = 'Self Extubation' then 1
	 else 0
	 end
	) as SelfExtubated
  FROM mimic3.CHARTEVENTS ce
  WHERE ce.value is not null AND (ce.error IS NULL or ce.error = 0) AND ce.itemid in
  (
	 640 -- extubated
	 , 720 -- vent type
	 , 467 -- O2 delivery device
	 , 445, 448, 449, 450, 1340, 1486, 1600, 224687 -- minute volume
	 , 639,654,681,682,683,684,2400,2408,2420,2534,3050,3083,224685,224684,224686 -- tidal volume
	 , 218,436,535,444,459,224697,224695,224696,224746,224747 -- High/Low/Peak/Mean/Neg insp force ("RespPressure")
	 , 221,1,1211,1655,2000,226873,224738,224419,224750,227187 -- Insp pressure
	 , 543,224696 -- PlateauPressure
	 , 5865,5866,224707,224709,224705,224706 -- APRV pressure
	 , 60,437,505,506,686,1096,1227,5964,6349,6350,6489,6601,6924,6943,7802,7803,220339,224699,224700 -- PEEP
	 , 3459 -- high pressure relief
	 , 501,502,503,224702 -- PCV
	 , 223,667,668,669,670,671,672 -- TCPCV
	 , 157,158,1852,3398,3399,3400,3401,3402,3403,3404,8382,227809,227810 -- ETT
	 , 224701 -- PSVlevel
  )
  group by icustay_id, charttime

ALTER TABLE mimic3_sepsis_cleaned.ALL_VASO_MV
ADD COLUMN rate_std NUMERIC(10, 3);

UPDATE mimic3_sepsis_cleaned.ALL_VASO_MV
SET rate_std =
    CASE
        when itemid in (30120,221906,30047) and rateuom='mcg/kg/min' then round(rate,3)  -- norad
        when itemid in (30120,221906,30047) and rateuom='mcg/min' then round(rate/80,3)  -- norad
        when itemid in (30119,221289,30309,30044) and rateuom='mcg/kg/min' then round(rate ,3) -- epi
        when itemid in (30119,221289,30309,30044) and rateuom='mcg/min' then round(rate/80 ,3) -- epi
        when itemid in (30051,222315) and rate > 0.2 then round(rate*5/60 ,3) -- vasopressin, in U/h
        when itemid in (30051,222315) and rateuom='units/min' then round(rate*5 ,3) -- vasopressin
        when itemid in (30051,222315) and rateuom='units/hour' then round(rate*5/60 ,3) -- vasopressin
        when itemid in (30128,221749,30127) and rateuom='mcg/kg/min' then round(rate*0.45 ,3) -- phenyl
        when itemid in (30128,221749,30127) and rateuom='mcg/min' then round(rate*0.45 / 80 ,3) -- phenyl
        when itemid in (221662,30043,30307) and rateuom='mcg/kg/min' then round(rate*0.01 ,3)  -- dopa
        when itemid in (221662,30043,30307) and rateuom='mcg/min' then round(rate*0.01/80 ,3) else null
    END
where itemid in (30128,30120,30051,221749,221906,30119,30047,30127,221289,222315,221662,30043,30307,30309,30044)

ALTER TABLE mimic3_sepsis_cleaned.ALL_VASO_CV
ADD COLUMN rate_std NUMERIC(10, 3);

UPDATE mimic3_sepsis_cleaned.ALL_VASO_CV
SET rate_std =
    CASE
        when itemid in (30120,221906,30047) and rateuom='mcgkgmin' then round(rate,3)  -- norad
        when itemid in (30120,221906,30047) and rateuom='mcgmin' then round(rate/80,3)  -- norad
        when itemid in (30119,221289,30309,30044) and rateuom='mcgkgmin' then round(rate ,3) -- epi
        when itemid in (30119,221289,30309,30044) and rateuom='mcgmin' then round(rate/80 ,3) -- epi
        when itemid in (30051,222315) and rate > 0.2 then round(rate*5/60 ,3) -- vasopressin, in U/h
        when itemid in (30051,222315) and rateuom='Umin' and rate < 0.2 then round(rate*5 ,3) -- vasopressin
        when itemid in (30051,222315) and rateuom='Uhr' then round(rate*5/60 ,3) -- vasopressin
        when itemid in (30128,221749,30127) and rateuom='mcgkgmin' then round(rate*0.45 ,3) -- phenyl
        when itemid in (30128,221749,30127) and rateuom='mcgmin' then round(rate*0.45 / 80 ,3) -- phenyl
        when itemid in (221662,30043,30307) and rateuom='mcgkgmin' then round(rate*0.01 ,3)  -- dopa
        when itemid in (221662,30043,30307) and rateuom='mcgmin' then round(rate*0.01/80 ,3) else null
    END
where itemid in (30128,30120,30051,221749,221906,30119,30047,30127,221289,222315,221662,30043,30307,30309,30044)



